// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.2

package com.elcom.eodapp.ehotel.ws;


public class XpossoapPortType_readMessage_ResponseStruct {
    protected java.lang.String responseCode;
    protected java.lang.String responseMessage;
    protected java.lang.String responseData;
    
    public XpossoapPortType_readMessage_ResponseStruct() {
    }
    
    public XpossoapPortType_readMessage_ResponseStruct(java.lang.String responseCode, java.lang.String responseMessage, java.lang.String responseData) {
        this.responseCode = responseCode;
        this.responseMessage = responseMessage;
        this.responseData = responseData;
    }
    
    public java.lang.String getResponseCode() {
        return responseCode;
    }
    
    public void setResponseCode(java.lang.String responseCode) {
        this.responseCode = responseCode;
    }
    
    public java.lang.String getResponseMessage() {
        return responseMessage;
    }
    
    public void setResponseMessage(java.lang.String responseMessage) {
        this.responseMessage = responseMessage;
    }
    
    public java.lang.String getResponseData() {
        return responseData;
    }
    
    public void setResponseData(java.lang.String responseData) {
        this.responseData = responseData;
    }
}
