// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.2

package com.elcom.eodapp.ehotel.ws;

import javax.xml.rpc.*;

public interface Xpossoap extends javax.xml.rpc.Service {
    public com.elcom.eodapp.ehotel.ws.XpossoapPortType getXpossoapPort() throws ServiceException;
}
