// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.2

package com.elcom.eodapp.ehotel.ws;


public class XpossoapPortType_postCharge_RequestStruct {
    protected java.lang.String sRoomNo;
    protected java.lang.String sGuestNo;
    protected double sAmount;
    
    public XpossoapPortType_postCharge_RequestStruct() {
    }
    
    public XpossoapPortType_postCharge_RequestStruct(java.lang.String sRoomNo, java.lang.String sGuestNo, double sAmount) {
        this.sRoomNo = sRoomNo;
        this.sGuestNo = sGuestNo;
        this.sAmount = sAmount;
    }
    
    public java.lang.String getSRoomNo() {
        return sRoomNo;
    }
    
    public void setSRoomNo(java.lang.String sRoomNo) {
        this.sRoomNo = sRoomNo;
    }
    
    public java.lang.String getSGuestNo() {
        return sGuestNo;
    }
    
    public void setSGuestNo(java.lang.String sGuestNo) {
        this.sGuestNo = sGuestNo;
    }
    
    public double getSAmount() {
        return sAmount;
    }
    
    public void setSAmount(double sAmount) {
        this.sAmount = sAmount;
    }
}
