
package com.elcom.eodapp.ehotel.sokha;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.elcom.eodapp.ehotel.common.xsd.OBill;
import com.elcom.eodapp.ehotel.common.xsd.OPost;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CoreSoKhaInterfacePortType", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
@XmlSeeAlso({
    com.elcom.eodapp.ehotel.common.xsd.ObjectFactory.class,
    com.elcom.eodapp.ehotel.sokha.ObjectFactory.class
})
public interface CoreSoKhaInterfacePortType {


    /**
     * 
     * @param guestRESERVATION
     * @param guestTITLE
     * @param roomSHAREFLAG
     * @param guestBIRTHDAY
     * @param guestTVRIGHT
     * @param guestLASTNAME
     * @param guestVIDEORIGHT
     * @param guestVIPSTATUS
     * @param guestDEPTDATE
     * @param guestLANGUAGE
     * @param guestARVDATE
     * @param guestFIRSTNAME
     * @param guestNAME
     * @param guestGROUP
     * @param guestROOM
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GuestCheckin", action = "urn:GuestCheckin")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "GuestCheckin", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestCheckin")
    @ResponseWrapper(localName = "GuestCheckinResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestCheckinResponse")
    public Boolean guestCheckin(
        @WebParam(name = "GUEST_ARV_DATE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestARVDATE,
        @WebParam(name = "GUEST_DEPT_DATE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestDEPTDATE,
        @WebParam(name = "GUEST_FIRST_NAME", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestFIRSTNAME,
        @WebParam(name = "GUEST_LAST_NAME", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestLASTNAME,
        @WebParam(name = "GUEST_NAME", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestNAME,
        @WebParam(name = "GUEST_RESERVATION", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestRESERVATION,
        @WebParam(name = "GUEST_ROOM", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestROOM,
        @WebParam(name = "GUEST_LANGUAGE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestLANGUAGE,
        @WebParam(name = "GUEST_GROUP", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestGROUP,
        @WebParam(name = "GUEST_TITLE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestTITLE,
        @WebParam(name = "GUEST_VIP_STATUS", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestVIPSTATUS,
        @WebParam(name = "GUEST_TV_RIGHT", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestTVRIGHT,
        @WebParam(name = "GUEST_VIDEO_RIGHT", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestVIDEORIGHT,
        @WebParam(name = "GUEST_BIRTHDAY", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestBIRTHDAY,
        @WebParam(name = "ROOM_SHARE_FLAG", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String roomSHAREFLAG);

    /**
     * 
     * @param fun
     * @return
     *     returns java.util.List<com.elcom.eodapp.ehotel.common.xsd.OPost>
     */
    @WebMethod(operationName = "GuestPostReq", action = "urn:GuestPostReq")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "GuestPostReq", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestPostReq")
    @ResponseWrapper(localName = "GuestPostReqResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestPostReqResponse")
    public List<OPost> guestPostReq(
        @WebParam(name = "fun", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String fun);

    /**
     * 
     * @param fun
     * @return
     *     returns java.util.List<com.elcom.eodapp.ehotel.common.xsd.OBill>
     */
    @WebMethod(operationName = "GuestBillReq", action = "urn:GuestBillReq")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "GuestBillReq", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestBillReq")
    @ResponseWrapper(localName = "GuestBillReqResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestBillReqResponse")
    public List<OBill> guestBillReq(
        @WebParam(name = "fun", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String fun);

    /**
     * 
     * @param guestRESERVATION
     * @param roomSHAREFLAG
     * @param guestROOM
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GuestCheckout", action = "urn:GuestCheckout")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "GuestCheckout", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestCheckout")
    @ResponseWrapper(localName = "GuestCheckoutResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestCheckoutResponse")
    public Boolean guestCheckout(
        @WebParam(name = "GUEST_RESERVATION", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestRESERVATION,
        @WebParam(name = "GUEST_ROOM", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestROOM,
        @WebParam(name = "ROOM_SHARE_FLAG", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String roomSHAREFLAG);

    /**
     * 
     * @param messageID
     * @param guestRESERVATION
     * @param messageTEXT
     * @param guestROOM
     * @param lastUPDATE
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GuestMessageTextOnline", action = "urn:GuestMessageTextOnline")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "GuestMessageTextOnline", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestMessageTextOnline")
    @ResponseWrapper(localName = "GuestMessageTextOnlineResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestMessageTextOnlineResponse")
    public Boolean guestMessageTextOnline(
        @WebParam(name = "GUEST_ROOM", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestROOM,
        @WebParam(name = "GUEST_RESERVATION", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestRESERVATION,
        @WebParam(name = "MESSAGE_ID", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String messageID,
        @WebParam(name = "MESSAGE_TEXT", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String messageTEXT,
        @WebParam(name = "LAST_UPDATE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String lastUPDATE);

    /**
     * 
     * @param itemAMOUNT
     * @param roomNUMER
     * @param time
     * @param itemDESC
     * @param displayFLAG
     * @param date
     * @param reservationNUMER
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GuestBillItem", action = "urn:GuestBillItem")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "GuestBillItem", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestBillItem")
    @ResponseWrapper(localName = "GuestBillItemResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestBillItemResponse")
    public Boolean guestBillItem(
        @WebParam(name = "ROOM_NUMER", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String roomNUMER,
        @WebParam(name = "RESERVATION_NUMER", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String reservationNUMER,
        @WebParam(name = "ITEM_DESC", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String itemDESC,
        @WebParam(name = "ITEM_AMOUNT", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String itemAMOUNT,
        @WebParam(name = "DISPLAY_FLAG", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String displayFLAG,
        @WebParam(name = "DATE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String date,
        @WebParam(name = "TIME", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String time);

    /**
     * 
     * @param guestRESERVATION
     * @param guestTITLE
     * @param roomSHAREFLAG
     * @param guestTVRIGHT
     * @param roomEXSHAREFLAG
     * @param guestLASTNAME
     * @param guestVIDEORIGHT
     * @param guestVIPSTATUS
     * @param guestEXROOM
     * @param guestDEPTDATE
     * @param guestLANGUAGE
     * @param guestARVDATE
     * @param guestFIRSTNAME
     * @param guestNAME
     * @param guestGROUP
     * @param guestROOM
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GuestRoomAndChangeMove", action = "urn:GuestRoomAndChangeMove")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "GuestRoomAndChangeMove", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestRoomAndChangeMove")
    @ResponseWrapper(localName = "GuestRoomAndChangeMoveResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestRoomAndChangeMoveResponse")
    public Boolean guestRoomAndChangeMove(
        @WebParam(name = "GUEST_EXROOM", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestEXROOM,
        @WebParam(name = "GUEST_RESERVATION", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestRESERVATION,
        @WebParam(name = "GUEST_ROOM", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestROOM,
        @WebParam(name = "ROOM_EXSHARE_FLAG", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String roomEXSHAREFLAG,
        @WebParam(name = "ROOM_SHARE_FLAG", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String roomSHAREFLAG,
        @WebParam(name = "GUEST_ARV_DATE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestARVDATE,
        @WebParam(name = "GUEST_DEPT_DATE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestDEPTDATE,
        @WebParam(name = "GUEST_FIRST_NAME", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestFIRSTNAME,
        @WebParam(name = "GUEST_LAST_NAME", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestLASTNAME,
        @WebParam(name = "GUEST_NAME", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestNAME,
        @WebParam(name = "GUEST_LANGUAGE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestLANGUAGE,
        @WebParam(name = "GUEST_GROUP", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestGROUP,
        @WebParam(name = "GUEST_TITLE", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestTITLE,
        @WebParam(name = "GUEST_VIP_STATUS", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestVIPSTATUS,
        @WebParam(name = "GUEST_TV_RIGHT", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestTVRIGHT,
        @WebParam(name = "GUEST_VIDEO_RIGHT", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestVIDEORIGHT);

    /**
     * 
     * @param guestRESERVATION
     * @param roomSHAREFLAG
     * @param guestEXROOM
     * @param guestROOM
     * @param roomEXSHAREFLAG
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GuestRoomMove", action = "urn:GuestRoomMove")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "GuestRoomMove", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestRoomMove")
    @ResponseWrapper(localName = "GuestRoomMoveResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.GuestRoomMoveResponse")
    public Boolean guestRoomMove(
        @WebParam(name = "GUEST_EXROOM", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestEXROOM,
        @WebParam(name = "GUEST_RESERVATION", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestRESERVATION,
        @WebParam(name = "GUEST_ROOM", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String guestROOM,
        @WebParam(name = "ROOM_EXSHARE_FLAG", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String roomEXSHAREFLAG,
        @WebParam(name = "ROOM_SHARE_FLAG", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String roomSHAREFLAG);

    /**
     * 
     * @param roomNUMER
     * @param reservationNUMER
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteBillItem", action = "urn:DeleteBillItem")
    @WebResult(targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
    @RequestWrapper(localName = "DeleteBillItem", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.DeleteBillItem")
    @ResponseWrapper(localName = "DeleteBillItemResponse", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com", className = "com.elcom.eodapp.ehotel.sokha.DeleteBillItemResponse")
    public Boolean deleteBillItem(
        @WebParam(name = "ROOM_NUMER", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String roomNUMER,
        @WebParam(name = "RESERVATION_NUMER", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
        String reservationNUMER);

}
