
package com.elcom.eodapp.ehotel.sokha;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.elcom.eodapp.ehotel.main.MainObject;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CoreSoKhaInterface", targetNamespace = "http://sokha.ehotel.eodapp.elcom.com")
public class CoreSoKhaInterface
    extends Service
{

    private final static URL CORESOKHAINTERFACE_WSDL_LOCATION;
    private final static WebServiceException CORESOKHAINTERFACE_EXCEPTION;
    private final static QName CORESOKHAINTERFACE_QNAME = new QName("http://sokha.ehotel.eodapp.elcom.com", "CoreSoKhaInterface");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(MainObject.config.eHotel_wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CORESOKHAINTERFACE_WSDL_LOCATION = url;
        CORESOKHAINTERFACE_EXCEPTION = e;
    }

    public CoreSoKhaInterface() {
        super(__getWsdlLocation(), CORESOKHAINTERFACE_QNAME);
    }

    public CoreSoKhaInterface(WebServiceFeature... features) {
        super(__getWsdlLocation(), CORESOKHAINTERFACE_QNAME, features);
    }

    public CoreSoKhaInterface(URL wsdlLocation) {
        super(wsdlLocation, CORESOKHAINTERFACE_QNAME);
    }

    public CoreSoKhaInterface(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CORESOKHAINTERFACE_QNAME, features);
    }

    public CoreSoKhaInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoreSoKhaInterface(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CoreSoKhaInterfacePortType
     */
    @WebEndpoint(name = "CoreSoKhaInterfaceHttpSoap11Endpoint")
    public CoreSoKhaInterfacePortType getCoreSoKhaInterfaceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://sokha.ehotel.eodapp.elcom.com", "CoreSoKhaInterfaceHttpSoap11Endpoint"), CoreSoKhaInterfacePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoreSoKhaInterfacePortType
     */
    @WebEndpoint(name = "CoreSoKhaInterfaceHttpSoap11Endpoint")
    public CoreSoKhaInterfacePortType getCoreSoKhaInterfaceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://sokha.ehotel.eodapp.elcom.com", "CoreSoKhaInterfaceHttpSoap11Endpoint"), CoreSoKhaInterfacePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns CoreSoKhaInterfacePortType
     */
    @WebEndpoint(name = "CoreSoKhaInterfaceHttpSoap12Endpoint")
    public CoreSoKhaInterfacePortType getCoreSoKhaInterfaceHttpSoap12Endpoint() {
        return super.getPort(new QName("http://sokha.ehotel.eodapp.elcom.com", "CoreSoKhaInterfaceHttpSoap12Endpoint"), CoreSoKhaInterfacePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoreSoKhaInterfacePortType
     */
    @WebEndpoint(name = "CoreSoKhaInterfaceHttpSoap12Endpoint")
    public CoreSoKhaInterfacePortType getCoreSoKhaInterfaceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://sokha.ehotel.eodapp.elcom.com", "CoreSoKhaInterfaceHttpSoap12Endpoint"), CoreSoKhaInterfacePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns CoreSoKhaInterfacePortType
     */
    @WebEndpoint(name = "CoreSoKhaInterfaceHttpEndpoint")
    public CoreSoKhaInterfacePortType getCoreSoKhaInterfaceHttpEndpoint() {
        return super.getPort(new QName("http://sokha.ehotel.eodapp.elcom.com", "CoreSoKhaInterfaceHttpEndpoint"), CoreSoKhaInterfacePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoreSoKhaInterfacePortType
     */
    @WebEndpoint(name = "CoreSoKhaInterfaceHttpEndpoint")
    public CoreSoKhaInterfacePortType getCoreSoKhaInterfaceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://sokha.ehotel.eodapp.elcom.com", "CoreSoKhaInterfaceHttpEndpoint"), CoreSoKhaInterfacePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CORESOKHAINTERFACE_EXCEPTION!= null) {
            throw CORESOKHAINTERFACE_EXCEPTION;
        }
        return CORESOKHAINTERFACE_WSDL_LOCATION;
    }

}
