// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.2

package com.elcom.eodapp.ehotel.ws;


public class XpossoapPortType_dbSwap_RequestStruct {
    
    public XpossoapPortType_dbSwap_RequestStruct() {
    }
}
